---
title: "Day 2"
format: html
editor: visual
---

[AdventOfCode](https://jrosell.github.io/AdventOfCode/) \> 2024

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(httr2)
})
adventofcode_input <- \(year, day) {
    session <- Sys.getenv("ADVENT_SESSION")
    if (session == "") {
    stop("Must set ADVENT_SESSION in .Renviron")
    }
    url <- paste0("https://adventofcode.com/", year, "/day/", day, "/input")
    tryCatch({
        res <- request(url) |> 
            req_cookies_set(session = session) |> 
            req_perform() |> 
            resp_body_string(encoding = "UTF-8")
        },
        error = \(e) stop("Error getting the input file")
    )
    data.frame(x = res |> strsplit("\n") |>  unlist())
}
```

## Part 1

```{r}
is_safe <- \(x){
    diffs <- diff(x, lag = 1, differences = 1)
    all(-diffs %in% 1:3) || all(diffs %in% 1:3)
}
tribble(
    ~x,
    "7 6 4 2 1",
    "1 2 7 8 9",
    "9 7 6 2 1",
    "1 3 2 4 5",
    "8 6 4 4 1",
    "1 3 6 7 9"
    ) |> 
    pull(x) |>
    str_split(" ") |> 
    map(as.numeric) |> 
    map_lgl(is_safe) |> 
    print()
```


```{r}
input <- adventofcode_input(2024, 2)
input |> 
    pull(x) |>
    str_split(" ") |> 
    map(as.numeric) |> 
    map_lgl(is_safe) |> 
    sum() |> 
    print()
```

## Part 2

if removing a single level from an unsafe report would make it safe, the report instead counts as safe.

    7 6 4 2 1: Safe without removing any level.
    1 2 7 8 9: Unsafe regardless of which level is removed.
    9 7 6 2 1: Unsafe regardless of which level is removed.
    1 3 2 4 5: Safe by removing the second level, 3.
    8 6 4 4 1: Safe by removing the third level, 4.
    1 3 6 7 9: Safe without removing any level.


```{r}
is_safe <- \(x){
    diffs <- diff(x, lag = 1, differences = 1)
    all(-diffs %in% 1:3) || all(diffs %in% 1:3)
}
is_safe_safe <- \(x) {
    result <- is_safe(x)
    if(!result) {
        indices <- seq_along(x)
        all_results <- map_lgl(indices, \(to_remove) {
            is_safe(x[-to_remove])
        })        
        result <- any(all_results)
    }
    return(result)
}
# report <- c(1,3,2,4,5)
# is_safe_safe(report)
```

```{r}
tribble(
    ~x,
    "7 6 4 2 1",
    "1 2 7 8 9",
    "9 7 6 2 1",
    "1 3 2 4 5",
    "8 6 4 4 1",
    "1 3 6 7 9"
    ) |> 
    pull(x) |>
    str_split(" ") |> 
    map(as.numeric) |> 
    map_lgl(is_safe_safe) |> 
    print()
```

```{r}
input <- adventofcode_input(2024, 2)
input |> 
    pull(x) |>
    str_split(" ") |> 
    map(as.numeric) |> 
    map_lgl(is_safe_safe) |> 
    sum() |> 
    print()
```
